### ISSUE TITLE
PetitFS?

### ISSUE THREAD

**Issue by vabatta** [gallegojm/Arduino-FatFs#1]
Hi,

great work!
You think that it's possible to do also the porting of petitfs? 

Thanks!

**Comment by gallegojm** [comment]
"great work!"
Thank you! But remember that the most part of that work is due to ChaN

"You think that it's possible to do also the porting of petitfs? "
Yes, I think you may refer to the sketch FatFsTest.ino
But did you consider to use SdFat? Or do you have a particular reason to prefer petitfs?

**Comment by vabatta** [comment]
I'm looking for a library with the smallest footprint and support for FAT 16/32.
Functions I need are:
fread
fwrite
fsize
ftruncate

So this is why I prefer PetitFS :)
